### PR TITLE
defaulting _complete to the shell of the parent process

### PR DESCRIPTION
**Pull request by EitanSchuler**
I have no idea if this is something you want, but it was a low-hanging fruit.

### CODE REVIEW

**Comment by perlpunk** [comment]
Thanks!
merged and added an extra check of the ps output

**Comment by perlpunk** [comment]
Just a recommendation, because I also made this mistake for my first pull request(s), and I see also other people doing this:
Always create a topic branch for pull requests, because:
* Creating a branch for everything and never work directly on master is a good habit and avoids rebasing
* If you create a pull request, any following commit you make will be automatically added to the pull request. This might not be wanted for master
* If you create a pull request in master, and then want to make another unrelated pull request, you can't do that in master
* If the recipient of the pull request does some other changes in between, you have to rebase your master. If on a branch, you can simply delete that branch after the PR is merged

**Comment by EitanSchuler** [comment]
Thanks, perlpunk, will do so in the future.

**Comment by perlpunk** [comment]
I found a bug: `ps` might return, for example: `-zsh`, `/bin/bash`, ...

**Pull request closed without merging**
